# Generated by Django 4.1.7 on 2023-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='percentage',
            field=models.ManyToManyField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], to='store.percentage'),
        ),
    ]
