# Generated by Django 4.1.7 on 2023-04-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_visit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelOtherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
                ('my_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mymodel')),
                ('other_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.othermodel')),
            ],
        ),
        migrations.AddField(
            model_name='mymodel',
            name='my_field',
            field=models.ManyToManyField(through='store.MyModelOtherModel', to='store.othermodel'),
        ),
    ]
