# Generated by Django 4.1.7 on 2023-04-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_mymodel_othermodel_mymodelothermodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mark', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courses', models.ManyToManyField(through='store.Enrollment', to='store.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='my_field',
        ),
        migrations.RemoveField(
            model_name='mymodelothermodel',
            name='my_model',
        ),
        migrations.RemoveField(
            model_name='mymodelothermodel',
            name='other_model',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='percentage_inti',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='detail',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='MyModelOtherModel',
        ),
        migrations.DeleteModel(
            name='OtherModel',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.student'),
        ),
    ]
