# Generated by Django 4.1.7 on 2023-04-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_territory'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='territory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Территория', to='store.territory'),
        ),
    ]
