# Generated by Django 4.1.7 on 2023-04-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_details_remove_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.percentage'),
        ),
    ]
