# Generated by Django 4.1.7 on 2023-04-17 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_details_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentage',
            name='percentage_int',
            field=models.IntegerField(null=True),
        ),
    ]
