# Generated by Django 4.1.7 on 2023-04-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_percentage_percentage_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='pro',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='percentage',
        ),
    ]
