# Generated by Django 4.1.7 on 2023-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_deteils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deteils',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='sku',
            field=models.ManyToManyField(blank=True, to='store.sku'),
        ),
    ]
