# Generated by Django 4.1.7 on 2023-04-19 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='user',
        ),
    ]
