# Generated by Django 4.1.7 on 2023-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_details_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage',
            name='percentage_int',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='user',
        ),
        migrations.AddField(
            model_name='visit',
            name='percentage',
            field=models.ManyToManyField(null=True, to='store.percentage'),
        ),
    ]
