# Generated by Django 4.1.7 on 2023-04-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_deteils_detail_alter_visit_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deteils',
            new_name='Details',
        ),
    ]
