# Generated by Django 4.1.7 on 2023-04-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sku_sku_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='sku_int',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
