# Generated by Django 4.1.7 on 2023-04-19 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_visit_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='percentage',
        ),
        migrations.AddField(
            model_name='visit',
            name='percentage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.percentage'),
        ),
    ]
