# Generated by Django 4.1.7 on 2023-04-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_visit_percentage_visit_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Percentage_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='protsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.percentage_1')),
                ('percentage_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.percentage_2')),
                ('percentage_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.percentage_3')),
                ('percentage_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.percentage_4')),
            ],
        ),
        migrations.AddField(
            model_name='percentage_4',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.protsent'),
        ),
        migrations.AddField(
            model_name='percentage_3',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.protsent'),
        ),
        migrations.AddField(
            model_name='percentage_2',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.protsent'),
        ),
        migrations.AddField(
            model_name='percentage_1',
            name='name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.protsent'),
        ),
    ]
