# Generated by Django 4.1.7 on 2023-04-19 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_percentage_1_percentage_2_percentage_3_percentage_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abdu', to='store.protsent'),
        ),
        migrations.AlterField(
            model_name='protsent',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_4',
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_1',
            field=models.ManyToManyField(blank=True, to='store.percentage_1'),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_2',
            field=models.ManyToManyField(blank=True, to='store.percentage_2'),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_3',
            field=models.ManyToManyField(blank=True, to='store.percentage_3'),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_4',
            field=models.ManyToManyField(blank=True, to='store.percentage_4'),
        ),
    ]
