# Generated by Django 4.1.7 on 2023-04-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_visit_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='sku_int',
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
