# Generated by Django 4.1.7 on 2023-04-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_sku_sku_int_visit_visit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='details',
            field=models.ManyToManyField(blank=True, to='store.details'),
        ),
    ]
