# Generated by Django 4.1.7 on 2023-04-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_test_name_of_alter_protsent_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentage_2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='percentage_3',
            name='name',
        ),
        migrations.RemoveField(
            model_name='percentage_4',
            name='name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='name_of',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_1',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_2',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_3',
        ),
        migrations.RemoveField(
            model_name='test',
            name='percentage_4',
        ),
        migrations.DeleteModel(
            name='Percentage_1',
        ),
        migrations.DeleteModel(
            name='Percentage_2',
        ),
        migrations.DeleteModel(
            name='Percentage_3',
        ),
        migrations.DeleteModel(
            name='Percentage_4',
        ),
        migrations.DeleteModel(
            name='protsent',
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_1',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_2',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_3',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='percentage_4',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], max_length=50, null=True),
        ),
    ]
