# Generated by Django 4.1.7 on 2023-04-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_visit_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.CharField(max_length=50)),
                ('nan', models.CharField(max_length=50)),
                ('choco', models.CharField(max_length=50)),
                ('cpw', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='procentage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.procentage'),
        ),
    ]
