# Generated by Django 4.1.7 on 2023-04-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_remove_percentage_2_name_remove_percentage_3_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Percentage_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='percentage_1',
            field=models.ForeignKey(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.percentage_1'),
        ),
    ]
