# Generated by Django 4.1.7 on 2023-04-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_procentage_visit_procentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='detail_pro',
        ),
        migrations.RemoveField(
            model_name='procentage',
            name='choco',
        ),
        migrations.RemoveField(
            model_name='procentage',
            name='cpw',
        ),
        migrations.RemoveField(
            model_name='procentage',
            name='nan',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='details',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='procentage',
        ),
        migrations.AlterField(
            model_name='procentage',
            name='coffee',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='United',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.details')),
                ('protc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.procentage')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='united',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.united'),
        ),
    ]
