# Generated by Django 4.1.7 on 2023-04-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_percentage_1_alter_test_percentage_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='percentage_1',
            name='per_int',
            field=models.IntegerField(null=True),
        ),
    ]
