# Generated by Django 4.1.7 on 2023-04-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_percentage_1_per_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='percentage_1',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='percentage',
        ),
        migrations.AddField(
            model_name='visit',
            name='perc_1',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='perc_2',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='perc_3',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='perc_4',
            field=models.CharField(blank=True, choices=[(10, '10%'), (20, '20%'), (30, '30%'), (40, '40%'), (50, '50%'), (60, '60%'), (70, '70%'), (80, '80%'), (90, '90%'), (100, '100%')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Percentage_1',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
