# Generated by Django 4.1.7 on 2023-04-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_visit_united_visit_united'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procentage',
            name='coffee',
        ),
        migrations.AddField(
            model_name='procentage',
            name='percent',
            field=models.IntegerField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='united',
            field=models.ManyToManyField(blank=True, to='store.united'),
        ),
    ]
