# Generated by Django 4.1.7 on 2023-04-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_visit_perc_1_alter_visit_perc_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='United',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='perc_1',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='perc_2',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='perc_3',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='perc_4',
        ),
        migrations.AddField(
            model_name='details',
            name='detail',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='united',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.details'),
        ),
        migrations.AddField(
            model_name='visit',
            name='united',
            field=models.ManyToManyField(blank=True, to='store.united'),
        ),
    ]
