# Generated by Django 4.1.7 on 2023-04-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_united_delete_percentage_remove_details_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='united',
            name='percent',
            field=models.CharField(choices=[('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('0%', '0%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=20, null=True),
        ),
    ]
