# Generated by Django 4.1.7 on 2023-04-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_united_protc_united_percent_delete_procentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='active',
        ),
    ]
