# Generated by Django 4.1.7 on 2023-04-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_details_user_visit_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='detail',
            new_name='name',
        ),
    ]
