# Generated by Django 4.1.7 on 2023-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_rename_detail_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
