# Generated by Django 4.1.7 on 2023-04-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_united_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='united',
            name='detail_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='united2', to='store.details'),
        ),
        migrations.AddField(
            model_name='united',
            name='detail_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='united3', to='store.details'),
        ),
        migrations.AddField(
            model_name='united',
            name='detail_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='united4', to='store.details'),
        ),
        migrations.AddField(
            model_name='united',
            name='percent_1',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='united',
            name='percent_2',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='united',
            name='percent_3',
            field=models.CharField(choices=[('0%', '0%'), ('10%', '10%'), ('20%', '20%'), ('30%', '30%'), ('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='0%', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='united',
            name='detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='united1', to='store.details'),
        ),
    ]
