# Generated by Django 4.1.7 on 2023-05-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_united_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_per', models.CharField(max_length=50)),
            ],
        ),
    ]
