# Generated by Django 4.1.7 on 2023-04-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_remove_united_detail_1_remove_united_detail_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='united',
            name='percent',
        ),
    ]
