# Generated by Django 4.1.7 on 2023-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_united_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='united',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='united',
            name='percent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
