# Generated by Django 4.1.7 on 2023-04-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_rename_detail_details_detail_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='detail_name',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='united',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
