# Generated by Django 4.1.7 on 2023-04-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_alter_details_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='united',
            name='percent',
        ),
        migrations.AlterField(
            model_name='united',
            name='detail',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
