# Generated by Django 4.1.7 on 2023-04-25 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0038_remove_united_percent_alter_united_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='detail',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='united',
            old_name='detail',
            new_name='name_detail',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='sku_name',
        ),
        migrations.AddField(
            model_name='details',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='united',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='detail',
            field=models.ManyToManyField(blank=True, to='store.details'),
        ),
    ]
