# Generated by Django 4.1.7 on 2023-04-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_rename_detail_details_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='date',
        ),
        migrations.AddField(
            model_name='sku',
            name='sku_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
