# Generated by Django 4.1.7 on 2023-04-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_remove_sku_date_sku_sku_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='detail',
            field=models.ManyToManyField(blank=True, null=True, to='store.details'),
        ),
    ]
